version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/api/src/Api/Dockerfile
    image: coursework-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__AppDbContext: Host=91.222.236.132;Port=5432;Database=db;Username=db;Password=db;
    ports:
      - "5000:8080"

  sso:
    build:
      context: .
      dockerfile: backend/sso/Dockerfile
    image: coursework-sso
    environment:
      SSO_ENV: docker
      SSO_CONNECTION_STRING: postgres://91.222.236.132:db@db:5432/db?sslmode=disable
      SSO_HTTP_PORT: "8080"
    ports:
      - "8080:8080"
