version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/api/src/Api/Dockerfile
    image: coursework-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__AppDbContext: Host=postgreSQL;Port=5432;Database=db;Username=db;Password=db;
    ports:
      - "5001:8080"
    networks:
      - pg_net

  sso:
    build:
      context: .
      dockerfile: backend/sso/Dockerfile
    image: coursework-sso
    environment:
      SSO_ENV: docker
      SSO_CONNECTION_STRING: postgres://postgreSQL:db@db:5432/db?sslmode=disable
      SSO_HTTP_PORT: "8081"
    ports:
      - "8081:8081"
    networks:
      - pg_net

networks:
  pg_net:
    external: true
